### ISSUE TITLE
[finetune] low GPU memory mode broken

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#146]
Tried to start finetune on A5000 and two times out of three had a problem:
![image](https://github.com/smallcloudai/refact/assets/140423660/1c73d0cf-6ed8-4bec-84b1-f3893cbba327)

```
stats: 102 good, 0 too large, 0 generated, 0 vendored
marking 102 files from test_120923.zip to which_set="train", to_db=False
total files 102
dedup...
after dedup 97 files
Reading /home/user/.refact/perm-storage/cfg/sources_filetypes.cfg
Will not overwrite '/home/user/.refact/tmp/unpacked-files/train_set.jsonl' because it is exactly the same as the current output
Will not overwrite '/home/user/.refact/tmp/unpacked-files/test_set.jsonl' because it is exactly the same as the current output
Will not overwrite '/home/user/.refact/tmp/unpacked-files/database_set.jsonl' because it is exactly the same as the current output
Train set filtering, loading model...
FILTER explanation: initial loss too big calculated on a single file, threshold is 3.500. Likely
means the file doesn't contain code.
Reading /home/user/.refact/perm-storage/cfg/sources_filetypes.cfg
calculated frames 55 
avg loss 1.2645
----------------------------------------TEST SET----------------------------------------
test set file: test_120923.zip/test_120923/src/utilities/dump_db.py
test set file: test_120923.zip/test_120923/src/enums/__init__.py
test set file: test_120923.zip/test_120923/data/scripts/rules/call_script_method_action.py
test set file: test_120923.zip/test_120923/data/scripts/rules/change_settings_action.py
test set file: test_120923.zip/test_120923/report_analyzer.py
Retrieving dataset length per epoch, it may take a while...
Dataset length per epoch = 34
Lora parameters heuristic avg_loss=1.26, ds_len=34 => complexity score=1
Selected the schedule by heuristics ds_len=34:
Total training steps: 50

Selected low_gpu_mem_mode=False by total gpu memory

Freeze exceptions: ['wte', 'lm_head', 'lora']
Lora config:  lora_target_modules ['qkv', 'out', 'mlp']
Lora config:               lora_r 64
Lora config:           lora_alpha 128
Lora config:         lora_dropout 0.01
Lora config:      lora_init_scale 0.01
creating model...
/model 3638.7ms
iter 0/50  tokens 0.000 input=128*4096 int64  mask=128*4096 bool (513766/524288)
switching to low GPU memory mode
FAILED: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

test4gpu-00 Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/refact-enterprise/refact_enterprise/finetune/finetune_train.py", line 14, in <module>
    main(models_mini_db)
  File "/home/user/refact/refact_data_pipeline/finetune/finetune_train.py", line 387, in main
    raise e
  File "/home/user/refact/refact_data_pipeline/finetune/finetune_train.py", line 374, in main
    finetune(status_dict, models_db)
  File "/home/user/refact/refact_data_pipeline/finetune/finetune_train.py", line 339, in finetune
    loop(
  File "/home/user/refact/refact_data_pipeline/finetune/finetune_train.py", line 231, in loop
    model.backward(loss)
  File "/home/user/.local/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1845, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/user/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1901, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/user/.local/lib/python3.9/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 62, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/user/.local/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/user/.local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
```

**Comment by JegernOUTT** [comment]
It looks like it couldn't free up the GPU memory, probably the due to the inefficient `vllm` unloading
It might be related with the https://github.com/smallcloudai/refact/issues/151

**Comment by JegernOUTT** [comment]
Might be fixed in https://github.com/smallcloudai/refact-enterprise/pull/8
