### ISSUE TITLE
Assert when unloading Refact/1.6B/vllm model

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact#151]
Refact/1.6B/vllm model working but when unloading:
```
- 30 -- 20230930 22:48:05 WEBUI required_memory_exceed_available 0
downloads-refact-1     | -- 30 -- 20230930 22:48:05 WEBUI more_models_than_gpus 0
downloads-refact-1     | -- 30 -- 20230930 22:48:05 WEBUI 172.31.2.1:34256 - "POST /tab-host-models-assign HTTP/1.1" 200
downloads-refact-1     | -- 30 -- 20230930 22:48:05 WEBUI 172.31.2.1:34256 - "GET /tab-host-models-get HTTP/1.1" 200
downloads-refact-1     | -- 2691 -- caught SIGUSR1Process Process-3:
downloads-refact-1     | -- 2691 -- Traceback (most recent call last):
downloads-refact-1     | -- 2691 --   File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
downloads-refact-1     | -- 2691 --     self.run()
downloads-refact-1     | -- 2691 --   File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
downloads-refact-1     | -- 2691 --     self._target(*self._args, **self._kwargs)
downloads-refact-1     | -- 2691 --   File "/usr/local/lib/python3.8/dist-packages/refact_enterprise/inference/vllm_machinery/task_manager.py", line 293, in _worker
downloads-refact-1     | -- 2691 --     self.requests_puller.stop()
downloads-refact-1     | -- 2691 --   File "/usr/local/lib/python3.8/dist-packages/refact_enterprise/inference/vllm_machinery/requests_puller.py", line 49, in stop
downloads-refact-1     | -- 2691 --     self.proc.join()
downloads-refact-1     | -- 2691 --   File "/usr/lib/python3.8/multiprocessing/process.py", line 147, in join
downloads-refact-1     | -- 2691 --     assert self._parent_pid == os.getpid(), 'can only join a child process'
downloads-refact-1     | -- 2691 -- AssertionError: can only join a child process
downloads-refact-1     | -- 30 -- 20230930 22:48:06 WEBUI 172.31.2.1:34256 - "GET /tab-host-have-gpus HTTP/1.1" 200
downloads-refact-1     | -- 30 -- 20230930 22:48:08 WEBUI 172.31.2.1:34256 - "GET /tab-host-have-gpus HTTP/1.1" 200
downloads-refact-1     | -- 30 -- 20230930 22:48:10 WEBUI 172.31.2.1:34256 - "GET /tab-host-have-gpus HTTP/1.1" 200
downloads-refact-1     | 20230930 22:48:12 2691 finished python -m refact_enterprise.inference.inference_worker --model Refact/1.6B/vllm @:gpu00, retcode 0
downloads-refact-1     | 20230930 22:48:12 cleanup model-refact-1.6b-vllm-00.cfg
```
But everything seems to work after that.

**Comment by JegernOUTT** [comment]
Should be fixed in https://github.com/smallcloudai/refact-enterprise/pull/8

**Comment by hazratisulton** [comment]
Checked - OK
