### ISSUE TITLE
Crash on Docker startup

### ISSUE THREAD

**Issue by LoopControl** [smallcloudai/refact#72]
When I try to start the docker command using the command given in the README, it immediately crashes with the following message (I've created the volume perm-storage manually and its the same result):

```
% docker run --rm -p 8008:8008 -v perm-storage:/perm_storage --gpus all smallcloud/refact_self_hosting 

==========
== CUDA ==
==========

CUDA Version 11.6.2

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/refact_self_hosting/watchdog.py", line 77, in <module>
    logdir.mkdir(exist_ok=True, parents=False)
  File "/usr/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/workdir/logs'
```

**Comment by LoopControl** [comment]
Sorry, seems the latest docker image hadn't been pulled and it was trying to run an old version.
